import { initializeApp } from 'firebase-admin/app';
initializeApp();

export { createOrganization } from './auth/createOrganization';
export { inviteUser } from './auth/inviteUser';
export { getOrgUsers } from './auth/getOrgUsers';
export { changeUserRole } from './auth/changeUserRole';
export { removeUser } from './auth/removeUser';
export { pcoOAuthCallback, pcoOAuthStart } from './pco/oauth';
export { getPcoResources } from './pco/resources';
export { triggerPcoSync } from './pco/sync';
export { scheduledPcoSync } from './pco/scheduledSync';
export { dispatchDoorCommands } from './scheduler/dispatcher';
export { updatePlatformConfig, getPlatformConfigCallable } from './admin/platformConfig';
export { getPlatformOverview, adminDeleteUser, adminDeleteTenant } from './admin/platformAdmin';
export { testPcoConnection, testUnifiConnection } from './config/testConnections';
export { generateAgentToken, registerAgentWithToken } from './agent/agentRegistration';
export { syncUnifiSchedules, saveUnifiSchedule, deleteUnifiSchedule } from './unifi/schedules';
export { syncUnifiVisitors, saveUnifiVisitor, deleteUnifiVisitor } from './unifi/visitors';
export { publishAgentRelease, getLatestAgentRelease, listAgentReleases, uploadAgentRelease, downloadAgentRelease } from './agent/releases';
